// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1NnMiBxV4D6Q6u1m5Dt5ohqka58e9kYk',
    appId: '1:427287208329:web:b837d33704e51007a90158',
    messagingSenderId: '427287208329',
    projectId: 'chat-app-8140e',
    authDomain: 'chat-app-8140e.firebaseapp.com',
    storageBucket: 'chat-app-8140e.appspot.com',
    measurementId: 'G-VHCE3G22N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4R9MnQwotlJNSArdJo6UUpYqYnZ782tg',
    appId: '1:427287208329:android:d52480b64ff07d08a90158',
    messagingSenderId: '427287208329',
    projectId: 'chat-app-8140e',
    storageBucket: 'chat-app-8140e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCVFI7AmzgKR7_pqR88FVssepSp8iAias',
    appId: '1:427287208329:ios:3e756406e93abd9fa90158',
    messagingSenderId: '427287208329',
    projectId: 'chat-app-8140e',
    storageBucket: 'chat-app-8140e.appspot.com',
    iosClientId: '427287208329-bjvdehl6t4kqobj81irl2jibgo7boq88.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCVFI7AmzgKR7_pqR88FVssepSp8iAias',
    appId: '1:427287208329:ios:3e756406e93abd9fa90158',
    messagingSenderId: '427287208329',
    projectId: 'chat-app-8140e',
    storageBucket: 'chat-app-8140e.appspot.com',
    iosClientId: '427287208329-bjvdehl6t4kqobj81irl2jibgo7boq88.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
